{
    "Teclado": "Keyboard",
    "Sim/Não": "Yes/No",
    "bem": "good",
    "mal": "bad",
    "Dor": "Pain",
    "Cuidados": "Care",
    "Como estou?": "How am I?",
    "Quanto tempo?": "How long?",
    "Eu": "I",
    "Você": "You",
    "estou": "am",
    "está": "is",
    "para": "for",
    "posso": "can",
    "quero": "want",
    "quer": "wants",
    "usar": "use",
    "ir": "go",
    "com": "with",
    "de": "of",
    "vontade": "will/urge",
    "sinto": "feel",
    "sente": "feels",
    "obrigado": "thank you",
    "desculpa": "sorry",
    "não sei": "I don't know",
    "Vontades": "Wishes",
    "Sintomas": "Symptoms",
    "Refeição": "Meal",
    "Higiene": "Hygiene",
    "Objetos": "Objects",
    "Emoções": "Emotions",
    "ajuda": "help",
    "mais comandos": "more commands",
    "sal": "salt",
    "açúcar": "sugar",
    "adoçante": "sweetener",
    "talheres": "cutlery",
    "colher": "spoon",
    "garfo": "fork",
    "faca": "knife",
    "canudo": "straw",
    "água": "water",
    "suco": "juice",
    "chá": "tea",
    "café": "coffee",
    "leite": "milk",
    "cerveja": "beer",
    "chocolate": "chocolate",
    "sopa": "soup",
    "legumes": "vegetables",
    "salada": "salad",
    "pão": "bread",
    "biscoito": "cookie",
    "torrada": "toast",
    "sanduíche": "sandwich",
    "cachorro quente": "hot dog",
    "omelete": "omelet",
    "presunto": "ham",
    "queijo": "cheese",
    "bolo": "cake",
    "sobremesa": "dessert",
    "sorvete": "ice cream",
    "picolé": "popsicle",
    "fruta": "fruit",
    "salada de frutas": "fruit salad",
    "maçã": "apple",
    "banana": "banana",
    "mamão": "papaya",
    "melão": "melon",
    "morango": "strawberry",
    "laranja": "orange",
    "melancia": "watermelon",
    "uva": "grape",
    "abacaxi": "pineapple",
    "pera": "pear",
    "gelatina": "gelatin",
    "iogurte": "yogurt",
    "arroz": "rice",
    "feijão": "beans",
    "purê": "mash",
    "carne": "meat",
    "frango": "chicken",
    "peixe": "fish",
    "ovo": "egg",
    "macarrão": "pasta",
    "batata frita": "french fries",
    "sem dor": "no pain",
    "dor leve": "mild pain",
    "dor moderada": "moderate pain",
    "dor intensa": "intense pain",
    "?": "?",
    "bom": "good",
    "ruim": "bad",
    "ficar": "stay",
    "outro": "other",
    "mais": "more",
    "menos": "less",
    "da": "of the (fem.)",
    "do": "of the (masc.)",
    "dia": "day",
    "mês": "month",
    "ano": "year",
    "segunda": "Monday",
    "terça": "Tuesday",
    "quarta": "Wednesday",
    "quinta": "Thursday",
    "sexta": "Friday",
    "sábado": "Saturday",
    "domingo": "Sunday",
    "amo": "love",
    "gosto": "like",
    "feliz": "happy",
    "triste": "sad",
    "inseguro": "insecure",
    "cansado": "tired",
    "medo": "fear",
    "fome": "hunger",
    "sem fome": "not hungry",
    "sede": "thirst",
    "sem sede": "not thirsty",
    "entubado": "intubated",
    "ansioso": "anxious",
    "aflito": "distressed",
    "pra baixo": "down",
    "gostando": "liking",
    "surpreso": "surprised",
    "vergonha": "shame",
    "aliviado": "relieved",
    "confiante": "confident",
    "irritado": "irritated",
    "deprimido": "depressed",
    "entediado": "bored",
    "pensativo": "thoughtful",
    "saudades": "missing you",
    "só": "alone",
    "torcer": "to root",
    "raiva": "anger",
    "viver": "live",
    "morrer": "die",
    "dor": "pain",
    "frio": "cold",
    "calor": "heat",
    "sono": "sleep",
    "febre": "fever",
    "falta de ar": "shortness of breath",
    "no corpo": "in the body",
    "no peito": "in the chest",
    "de cabeça": "headache",
    "no ouvido": "in the ear",
    "de garganta": "sore throat",
    "de dente": "toothache",
    "nas pernas": "in the legs",
    "nas costas": "in the back",
    "nas mãos": "in the hands",
    "nos pés": "in the feet",
    "nas nádegas": "in the buttocks",
    "fraco": "weak",
    "mal-estar": "discomfort",
    "ferida": "wound",
    "coceira": "itch",
    "erupção": "rash",
    "dormência": "numbness",
    "inchaço": "swelling",
    "suando muito": "sweating heavily",
    "tontura": "dizziness",
    "vista turva": "blurred vision",
    "desmaio": "fainting",
    "falta de apetite": "lack of appetite",
    "náusea": "nausea",
    "vômito": "vomit",
    "diarréia": "diarrhea",
    "no estômago": "in the stomach",
    "na barriga": "in the belly",
    "gases": "gas",
    "prisão de ventre": "constipation",
    "boca amarga": "bitter mouth",
    "muita saliva": "much saliva",
    "afta": "canker sore",
    "azia": "heartburn",
    "soluço": "hiccup",
    "queimação": "burning sensation",
    "calafrio": "chill",
    "respiração difícil": "difficult breathing",
    "ao respirar": "when breathing",
    "coração acelerado": "fast heartbeat",
    "ansiedade": "anxiety",
    "membros frios": "cold limbs",
    "no braço": "in the arm",
    "chiado no peito": "wheezing",
    "nariz entupido": "stuffy nose",
    "tosse": "cough",
    "catarro": "phlegm",
    "cera no ouvido": "earwax",
    "zumbido": "tinnitus",
    "dificuldade de urinar": "difficulty urinating",
    "dificuldade de defecar": "difficulty defecating",
    "urina escura": "dark urine",
    "ao urinar": "when urinating",
    "chamar enfermaria": "call nursing staff",
    "chamar médico": "call doctor",
    "chamar familiar": "call family member",
    "tomar remédio": "take medicine",
    "saber a medicação": "know the medication",
    "resultado de exame": "exam result",
    "saber sobre alta": "know about discharge",
    "aferir a pressão": "check blood pressure",
    "ver a saturação": "check saturation",
    "medir a glicose": "measure glucose",
    "aferir grau": "check temperature",
    "trocar soro": "change IV drip",
    "trocar de posição": "change position",
    "ser examinado": "be examined",
    "oxigênio": "oxygen",
    "inalação": "inhalation",
    "conferir a sonda": "check the tube",
    "conferir a bolsa": "check the bag",
    "usar a máscara": "use the mask",
    "ver o monitor": "see the monitor",
    "trocar curativo": "change dressing",
    "exame de sangue": "blood test",
    "exame de urina": "urine test",
    "exame de fezes": "stool test",
    "raio-x": "X-ray",
    "eletro": "ECG",
    "ultrassom": "ultrasound",
    "tomografia": "tomography",
    "colono": "colonoscopy",
    "trocar roupa": "change clothes",
    "fazer xixi": "pee",
    "fazer cocô": "poop",
    "lavar as mãos": "wash hands",
    "escovar os dentes": "brush teeth",
    "tomar banho": "take a bath/shower",
    "lavar o cabelo": "wash hair",
    "pentear o cabelo": "comb/brush hair",
    "hidratar o corpo": "moisturize body",
    "limpar axilas": "clean armpits",
    "trocar fralda": "change diaper",
    "secar": "dry",
    "limpar os olhos": "clean eyes",
    "me vestir": "dress myself",
    "silêncio": "silence",
    "beber": "drink",
    "comer": "eat",
    "dormir": "sleep",
    "sentar": "sit",
    "levantar": "stand up",
    "me mexer": "move myself",
    "caminhar": "walk",
    "passear": "go for a walk",
    "assistir": "watch",
    "ouvir": "listen",
    "fazer": "do/make",
    "ligar": "turn on",
    "desligar": "turn off",
    "pedir": "ask for",
    "trocar": "change/switch",
    "ver": "see",
    "fumar": "smoke",
    "celular": "cellphone",
    "internet": "internet",
    "tablet": "tablet",
    "livro": "book",
    "óculos": "glasses",
    "lentes": "contacts",
    "jornal": "newspaper",
    "revista": "magazine",
    "caderno": "notebook",
    "caneta": "pen",
    "controle": "remote control",
    "pente": "comb",
    "escova": "brush",
    "boné": "cap",
    "meias": "socks",
    "sapatos": "shoes",
    "bengala": "cane",
    "andador": "walker",
    "muletas": "crutches",
    "relógio": "watch",
    "carregador": "charger",
    "bolsa": "bag",
    "carteira": "wallet",
    "SIM": "YES",
    "NÃO": "NO",
    "Espaço": "Space",
    ".": ".",
    ",": ",",
    "!": "!"
}